config/routes.rb
Inkerage::Application.routes.draw do
  devise_for :artists, :controllers => { :sessions => "artists/sessions", :registrations => "artists/registrations"}
  devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations" }
  
  get '/users/profile', :to => 'users#profile', :as => "user_profile"
  post '/new', :to => 'users#profile'

  get '/artists/profile', :to => 'artists#profile', :as => "artist_profile"
  
  get '/index', :to => 'designs#index', :as => "design_index"
  post '/users/profile', :to => 'designs#add_fav'
  delete '/users/profile/:id', :to => 'users#delete', :as => "delete_pic"


  root :to => "home#index"

end


#         new_artist_session GET    /artists/sign_in(.:format)       artists/sessions#new
#             artist_session POST   /artists/sign_in(.:format)       artists/sessions#create
#     destroy_artist_session DELETE /artists/sign_out(.:format)      artists/sessions#destroy
#            artist_password POST   /artists/password(.:format)      devise/passwords#create
#        new_artist_password GET    /artists/password/new(.:format)  devise/passwords#new
#       edit_artist_password GET    /artists/password/edit(.:format) devise/passwords#edit
#                            PUT    /artists/password(.:format)      devise/passwords#update
# cancel_artist_registration GET    /artists/cancel(.:format)        artists/registrations#cancel
#        artist_registration POST   /artists(.:format)               artists/registrations#create
#    new_artist_registration GET    /artists/sign_up(.:format)       artists/registrations#new
#   edit_artist_registration GET    /artists/edit(.:format)          artists/registrations#edit
#                            PUT    /artists(.:format)               artists/registrations#update
#                            DELETE /artists(.:format)               artists/registrations#destroy
#           new_user_session GET    /users/sign_in(.:format)         users/sessions#new
#               user_session POST   /users/sign_in(.:format)         users/sessions#create
#       destroy_user_session DELETE /users/sign_out(.:format)        users/sessions#destroy
#              user_password POST   /users/password(.:format)        devise/passwords#create
#          new_user_password GET    /users/password/new(.:format)    devise/passwords#new
#         edit_user_password GET    /users/password/edit(.:format)   devise/passwords#edit
#                            PUT    /users/password(.:format)        devise/passwords#update
#   cancel_user_registration GET    /users/cancel(.:format)          users/registrations#cancel
#          user_registration POST   /users(.:format)                 users/registrations#create
#      new_user_registration GET    /users/sign_up(.:format)         users/registrations#new
#     edit_user_registration GET    /users/edit(.:format)            users/registrations#edit
#                            PUT    /users(.:format)                 users/registrations#update
#                            DELETE /users(.:format)                 users/registrations#destroy
#               user_profile GET    /users/profile(.:format)         users#profile
#                        new POST   /new(.:format)                   users#profile
#             artist_profile GET    /artists/profile(.:format)       artists#profile
#               design_index GET    /index(.:format)                 designs#index
#              users_profile POST   /users/profile(.:format)         designs#add_fav
#                 delete_pic DELETE /users/profile/:id(.:format)     users#delete
#                       root        /                                home#index

app/models/artist.rb
class Artist < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :designs
  has_many :users
end

app/models/design.rb
class Design < ActiveRecord::Base
  attr_accessible :url

  belongs_to :user
  belongs_to :artist
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :designs
  has_many :artists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists/registrations_controller.rb
class Artists::RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(resource)
    user_profile_path
  end
end

app/controllers/artists/sessions_controller.rb
class Artists::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    stored_location_for(resource) || artist_profile_path
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    
  end

  def profile

  end

  def new
    @artist = Artist.new
  end

end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController

  def index
  
  client = Tumblr::Client.new(:client => :httpclient)
  @picture = client.posts("blackdwork.tumblr.com/", :type => "photo", :limit => 150)
  @pix = client.posts("get-fucked-and-get-inked.tumblr.com/", :type => "photo", :limit => 200)
  @img = client.posts("tattoosandtutus.tumblr.com/", :type => "photo", :limit => 200)
  #use the @variable if you want to display it in views
  end

  def add_fav
    design = Design.new(params[:designs])
    design.save
    current_user.designs << design 
    redirect_to '/users/profile'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index

  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(resource)
    user_profile_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    stored_location_for(resource) || user_profile_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'tumblr_client'

  def index

  end

  def profile
    @design = current_user.designs
  end

  def delete
    Design.find(params[:id]).delete 
    redirect_to '/users/profile'
  end

  # def new
  #   @user = User.new
  # end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_artist_form.html.erb
<%= form_for artist do |f| %>
  <%= f.label "Username" %>
  <%= f.text_area :username, :size => "20" %>
  <%= f.label "Name" %>
  <%= f.text_area :name, size: "20" %>
  <%= f.label "Location" %>
  <%= f.text_area :location, size: "20" %>
  <%= f.label "Bio" %>
  <%= f.text_area :bio, size: "200" %>
  <%= f.label "Experience" %>
  <%= f.text_area :experience, size: "50" %>
  <%= f.submit %>

<% end %>

app/views/artists/new.html.erb
Please create your profile:

<%= render :partial => "artist_form", :locals => {:artist => @artist} %>

app/views/artists/profile.html.erb
<wrapper class="container">
<div class="offset-by-five">
  <h4>Artist's profile</h4>
  <ul>
    <% @design.each do |design| %>

</div>
</wrapper>

app/views/designs/index.html.erb
<container class="container">


  <div class="offset-by-five images">
  <h4 class="headers">Add to Favorites!</h4>

  <% @picture["posts"].each do |pic| %>
    <%= form_tag('/users/profile', :method => :post) do |f| %>
      <% img = pic["photos"][0]['alt_sizes'][1]["url"] %>
      <img src="<%= img %>" /><br />
      <input type="hidden" name="designs[url]" value="<%= img %>">
      <input type="submit" value="Add Favorites!" />
      <br />
    <% end %>
  <% end %>

   <% @img["posts"].each do |img| %>
    <%= form_tag('/users/profile', :method => :post) do |f| %>
      <% img = img["photos"][0]['alt_sizes'][1]["url"] %>
      <img src="<%= img %>" /><br />
      <input type="hidden" name="designs[url]" value="<%= img %>">
      <input type="submit" value="Add Favorites!" />
      <br />
    <% end %>
  <% end %>
    
  <% @pix["posts"].each do |pic1| %>
    <%= form_tag('/users/profile', :method => :post) do |f| %>
      <% img = pic1["photos"][0]['alt_sizes'][1]["url"] %>
      <img src="<%= img %>" /><br />
      <input type="hidden" name="designs[url]" value="<%= img %>">
      <input type="submit" value="Add Favorites!" />
      <br />
    <% end %>
  <% end %>
</div>
</container>

app/views/home/index.html.erb
<container class="container">


  <div class="offset-by-five devise">

    Please <%= link_to("Sign up", new_user_registration_path) %>! <br />
         Have an account? <%= link_to("Sign in", new_user_session_path) %>
    <br />
    <br />
    If you are an Artist please <%= link_to("Join", new_artist_registration_path)%>! <br />
      Have an Artist account? <%= link_to("Sign in", new_artist_session_path)%>!

  </div>
</container>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inkerage</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<containter class="container">
<div class="nav">
  <h1 class="offset-by-three eight columns text" id="title">Inkerage!</h1>
  <div class="text">
    <% if user_signed_in? %>
      Logged in as <%= current_user.email %> | <%= link_to("log out as User", destroy_user_session_path, :method => :delete) %><br /> Go back to <%= link_to "My Profile", user_profile_path %> | Log out of <%= link_to "Artist", destroy_artist_session_path, :method => :delete %><br />
      <!-- <h4>View more <%= link_to "Tattoos", design_index_path %>!</h4> -->
    <% end %>
</div>
</div>
</containter>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<div class="footer">
</div>
<%= yield %>

</body>
</html>

app/views/users/_user_form.html.erb
<%= form_for user do |f| %>
  <%= f.label "Username" %>
  <%= f.text_field :username, :size => "20", :placeholder => "username" %>
  <%= f.label "Contact" %>
  <%= f.text_field :contact, size: "50", :placeholder => "contact"%>
  <%= f.label "Picture" %>
  <%= f.text_field :profile_pic, size: "50", :placeholder => "put in URL" %>

  <%= f.submit %>

<% end %>

app/views/users/new.html.erb
Please create your user profile:

<%= render :partial => "user_form", :locals => {:user => @user} %>

app/views/users/profile.html.erb
<wrapper class="container">
<div class="offset-by-five images">
<h4 class="headers">This is your profile!</h4>
  <!-- Create new <%= link_to "profile", users_profile_path %> -->
  <div class="line">Hello, <%= current_user.email %>! | Please add some <%= link_to "Tattoos", design_index_path %> to your fav list!</div>
<ul>
  <% @design.each do |design| %>
    <li><img src="<%= design.url %>"></li>
    <%= link_to("Delete Pic", delete_pic_path(design), :method => :delete) %>
  <% end %>
</ul>
</div>
</wrapper>